#!/usr/bin/env bash
set -e

BASE="docs"

# Create docs directory safely
mkdir -p "$BASE"

declare -A STRUCTURE=(
  ["introduction"]="OVERVIEW.md VISION.md GLOSSARY.md FAQ.md"
  ["sovereign-legal"]="LICENSE.md SOVEREIGN-DECREE.md ACCESS-RESTRICTIONS.md DATA-SOVEREIGNTY.md COMPLIANCE-OBLIGATIONS.md AUDIT-GUIDELINES.md"
  ["architecture"]="HIGH-LEVEL.md BANKCHAIN-ROUTING.md CIVICCHAIN-FLOW.md MULTI-CHAIN-EXECUTION.md PI-ECOSYSTEM-INTEGRATION.md DATA-FLOW-DIAGRAMS.md INFRASTRUCTURE-MAPS.md"
  ["identity"]="IDENTITY-FRAMEWORK.md WALLET-CONNECT.md CITIZEN-ACCESS.md INSTITUTION-ACCESS.md AUTHENTICATION-FLOWS.md KYC-AML-PROCEDURES.md"
  ["bankchain"]="OVERVIEW.md FIAT-CRYPTO-RAILS.md ISO20022-PIPELINES.md SETTLEMENT-FLOWS.md COMPLIANCE-ENGINE.md AI-MONITORING.md API-GUIDE.md"
  ["civicchain"]="GOVERNANCE-MODEL.md VOTING-PROTOCOL.md PUBLIC-RECORDS.md CIVIC-MIXER.md CONSTITUTION-INTEGRATION.md"
  ["smart-city"]="PI-SMART-CITY.md PITAXI.md ELMAHROSA-MAP.md GEO-IOT.md CITY-DASHBOARDS.md"
  ["apis"]="INTRODUCTION.md AUTHENTICATION.md RATE-LIMITS.md"
  ["apis/rest"]="BANKCHAIN-REST.md CIVICCHAIN-REST.md IDENTITY-REST.md ADMIN-REST.md"
  ["apis/websocket"]="STREAMS.md EVENT-TYPES.md"
  ["apis/blockchain"]="SOLANA-PROGRAMS.md PI-NETWORK.md ELMAHROSA-CHAIN.md"
  ["security"]="SECURITY-MODEL.md ENCRYPTION.md THREAT-MODEL.md INCIDENT-RESPONSE.md PENETRATION-GUIDELINES.md AUDIT-TRAILS.md"
  ["deployment"]="LOCAL-SETUP.md STAGING.md PRODUCTION.md VERSEL-DEPLOY.md DOCKER-CONTAINERS.md CLOUD-INFRA.md"
  ["operations"]="MONITORING.md LOGGING.md BACKUPS.md FAILOVER.md MAINTENANCE.md"
  ["ai-automation"]="AI-AUDITOR.md RISK-SCORING.md FRAUD-DETECTION.md AUTOVERIFICATION.md SERVICE-RECOMMENDER.md"
  ["governance"]="CIVIC-BLOCKCHAIN-CONSTITUTION.md GOVERNANCE-RULES.md DECISION-MAKING.md PUBLIC-TRANSPARENCY.md"
  ["branding"]="BRAND-GUIDE.md LOGO-USAGE.md UI-COMPONENTS.md TYPOGRAPHY.md COLOR-SYSTEM.md"
  ["roadmap"]="2025.md 2026.md BEYOND.md"
  ["changelog"]="v1.md v2.md v2.1.md"
)

for DIR in "${!STRUCTURE[@]}"; do
  TARGET="$BASE/$DIR"
  mkdir -p "$TARGET"

  for FILE in ${STRUCTURE[$DIR]}; do
    FILEPATH="$TARGET/$FILE"

    if [ ! -e "$FILEPATH" ]; then
      echo "# ${FILE%.*}" > "$FILEPATH"
      echo "Created: $FILEPATH"
    else
      echo "Skipped (already exists): $FILEPATH"
    fi
  done
done

echo "✔ Documentation structure generated successfully!"
